language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run go
after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
notifications:
  email:
    on_failure: change
    on_success: change
